In [1]:
import torch

x = torch.tensor([[1, 2]])
y = torch.tensor([[1], [2]])
print(x.shape, y.shape, x.dtype)

torch.Size([1, 2]) torch.Size([2, 1]) torch.int64


In [2]:
x = torch.tensor([False, 1, 2.0])
print(x)

tensor([0., 1., 2.])


In [3]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
torch.randint(0, 10, size=(3, 4))

tensor([[6, 2, 4, 2],
        [2, 2, 5, 8],
        [0, 9, 3, 5]])

In [6]:
torch.rand(3, 4)

tensor([[0.5092, 0.3602, 0.6874, 0.7004],
        [0.2486, 0.8437, 0.9772, 0.2134],
        [0.3555, 0.6879, 0.4364, 0.7123]])

In [7]:
torch.randn(3, 4)

tensor([[ 0.3890,  0.3967,  0.1461,  0.5614],
        [ 0.3534, -0.5635,  1.1341,  0.6009],
        [-0.7479,  0.6088,  0.3857, -0.7835]])

In [8]:
import numpy as np

x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


---