In [1]:
x = [[1,2],[3,4],[5,6],[7,8]]
y = [[3],[7],[11],[15]]

In [2]:
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import Dataset, DataLoader
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
class MyDataset(Dataset):
    def __init__(self, x, y):
        self.x = torch.tensor(x).float().to(device)
        self.y = torch.tensor(y).float().to(device)
    def __getitem__(self, ix):
        return self.x[ix], self.y[ix]
    def __len__(self): 
        return len(self.x)

In [4]:
ds = MyDataset(x, y)
dl = DataLoader(ds, batch_size=2, shuffle=True)

In [5]:
model = nn.Sequential(
    nn.Linear(2, 8),
    nn.ReLU(),
    nn.Linear(8, 1)
).to(device)

In [6]:
!pip install torch_summary
from torchsummary import summary

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


In [7]:
summary(model, torch.zeros(1,2));

Layer (type:depth-idx)                   Output Shape              Param #
├─Linear: 1-1                            [-1, 8]                   24
├─ReLU: 1-2                              [-1, 8]                   --
├─Linear: 1-3                            [-1, 1]                   9
Total params: 33
Trainable params: 33
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00


In [8]:
loss_func = nn.MSELoss()
from torch.optim import SGD
opt = SGD(model.parameters(), lr = 0.001)
import time
loss_history = []
start = time.time()
for _ in range(50):
    for ix, iy in dl:
        opt.zero_grad()
        loss_value = loss_func(model(ix),iy)
        loss_value.backward()
        opt.step()
        loss_history.append(loss_value)
end = time.time()
print(end - start)

0.17158722877502441


In [9]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.2646, -0.4421],
                      [ 0.5583,  0.7821],
                      [ 1.0661,  0.0423],
                      [ 0.2332, -0.4874],
                      [ 0.2819, -0.2207],
                      [-0.2685, -0.2712],
                      [ 0.4094, -0.3873],
                      [ 0.0134, -0.3315]], device='cuda:0')),
             ('0.bias',
              tensor([-0.3145,  0.0134,  0.1588,  0.3568, -0.4909, -0.0978,  0.0089, -0.2433],
                     device='cuda:0')),
             ('2.weight',
              tensor([[-7.1367e-04,  8.8423e-01,  7.5023e-01, -1.5604e-01, -2.6649e-01,
                       -2.0560e-02, -5.1880e-02, -1.9220e-01]], device='cuda:0')),
             ('2.bias', tensor([0.0551], device='cuda:0'))])

## Saving

In [10]:
save_path = 'mymodel.pth'
torch.save(model.state_dict(), save_path)
!du -hsc {save_path} # size of the model on disk

4.0K	mymodel.pth
4.0K	total


## Loading

In [11]:
load_path = 'mymodel.pth'
model.load_state_dict(torch.load(load_path))

<All keys matched successfully>

## Predictions

In [12]:
val = [[8,9],[10,11],[1.5,2.5]]
val = torch.tensor(val).float()

In [13]:
model(val.to(device))

tensor([[17.0439],
        [21.0776],
        [ 3.9346]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [14]:
val.sum(-1)

tensor([17., 21.,  4.])

---